### PR TITLE
patches to make it compile in Haiku Beta 1 and on 64-bits.

### PR DESCRIPTION
**Pull request by rogueeve575**
Hi, I'm the original author of "Sisong IDE". I ran across this nice repo you guys have of the 2009 BeOS version of it while I was doing some recent work on it's descendant (I still use this program all the time; but it's long since been ported to Linux using a beos-api compatibility library I wrote).

I didn't know that it didn't compile on latest haiku, or that I had done a bunch of stupid invalid C++ stuff at the time that GCC3 was letting me get away with.

FWIW, this seems to fix it so that it compiles and runs again. I got rid of a bunch of default arguments given to functions in .cpp files instead of headers, regenerated the .fdh "function definition headers" using the latest version of the makegen tool I use, and ripped out references to my "smal" memory-leak detection library which I was into at the time, since it was stupid, and fatally flawed on 64-bits because it assumed a pointer was 4 bytes.

Since this is (to me anyway) a very old version, my time would probably be better be spent working on polishing the new version for release, but at least this version does not have to be _entirely_ horribly broken.

### CODE REVIEW

**Comment by humdingerb** [comment]
Thanks for the patch!
Do I need some 3rd lib for compilation. gcc8 under 32bit Haiku fails to build:

```
[x86] /Source/Sisong/src> make
g++ -g -c MainWindow.cpp -Wno-narrowing -Wno-write-strings -Wno-multichar -Wno-unused-result -Wunused-variable -o MainWindow.o
In file included from editor.h:59,
                 from MainWindow.cpp:2:
line.h:3:10: fatal error: line.fdh: No such file or directory
 #include "line.fdh"
          ^~~~~~~~~~
compilation terminated.
Makefile:50: recipe for target 'MainWindow.o' failed
make: *** [MainWindow.o] Error 1

```

**Comment by rogueeve575** [comment]
Oops!... Those are just auto-generated header files with function prototypes in them. It looks like they were in my .gitignore file so some of them were missing and I didn't get notified in git commit -a. I guess I wasn't tracking them since they would be auto-generated, but that doesn't make since for publishing since other people won't have my special "makegen" program. I do far more coding than releasing so whoops...thanks for checking.

 I fixed and updated the repo. And this time, double-checked with a clean clone in a Haiku Beta R1 VM.

 git clone https://www.github.com/rogueeve575/Sisong
 cd Sisong
 cd src
 make
 ./sisong
 March 7 2020 4:40 AM, "humdinger"  wrote:  

	  
	Thanks for the patch!
 Do I need some 3rd lib for compilation. gcc8 under 32bit Haiku fails to build: 

	 [x86] /Source/Sisong/src> make g++ -g -c MainWindow.cpp -Wno-narrowing -Wno-write-strings -Wno-multichar -Wno-unused-result -Wunused-variable -o MainWindow.o In file included from editor.h:59, from MainWindow.cpp:2: line.h:3:10: fatal error: line.fdh: No such file or directory #include "line.fdh" ^~~~~~~~~~ compilation terminated. Makefile:50: recipe for target 'MainWindow.o' failed make: *** [MainWindow.o] Error 1

**Comment by rogueeve575** [comment]
Note that I was using 64-bit Haiku...for 32-bit Haiku I had to add a few tiny tweaks just now, because of the hybrid compiler thing. GCC2.95 doesn't have the warning options like -Wno-narrowing that caused errors when compiling with modern GCC if they were missing. And on 32-bit it seems GCC2.95 is the default "gcc" and the modern one is called "gcc-x86"? However I can't change the Makefile to use gcc-x86 by default because that doesn't exist on 64-bit.

 So to compile with GCC2.95, "cp Makefile.gcc2 Makefile"

 To use the modern compiler, I guess you'd want to find/replace all of the "gcc" in the Makefile with "gcc-x86", if you are on 32-bits.

 Either compiler the produced program seems to work fine...
 March 7 2020 4:40 AM, "humdinger"  wrote:  

	  
	Thanks for the patch!
 Do I need some 3rd lib for compilation. gcc8 under 32bit Haiku fails to build: 

	 [x86] /Source/Sisong/src> make g++ -g -c MainWindow.cpp -Wno-narrowing -Wno-write-strings -Wno-multichar -Wno-unused-result -Wunused-variable -o MainWindow.o In file included from editor.h:59, from MainWindow.cpp:2: line.h:3:10: fatal error: line.fdh: No such file or directory #include "line.fdh" ^~~~~~~~~~ compilation terminated. Makefile:50: recipe for target 'MainWindow.o' failed make: *** [MainWindow.o] Error 1

**Comment by humdingerb** [comment]
Thanks. Compiles now with gcc2 and gcc8 on 32bit.

FWIW, you don't need to make stuff work for gcc2. Haiku 32bit is always a hybrid with gcc2 and gcc8+, 64bit is gcc8+ onlly. With 32bit Haiku, you just do a "setarch x86" and you'll be using gcc8 for that session.

**Comment by humdingerb** [comment]
Merged, thank you!
